version: '3.7'

services:
  pugtube:
    build:
      context: .
      dockerfile: Dockerfile
    image: pugtube
    working_dir: /app
    ports:
      - "3000:3000"

  s3:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio
    volumes:
      - s3_data:/data
volumes:
  db_data:
  s3_data: