version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: .docker/web.dockerfile
      args:
        DOTENV_KEY: ${DOTENV_KEY}
        NODE_ENV: ${NODE_ENV}
    image: abdulachik/pugtube
    working_dir: /app
    environment:
      - REDIS_URL=redis://cache:6379
    depends_on:
      cache:
        condition: service_healthy
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: .docker/worker.dockerfile
      args:
        DOTENV_KEY: ${DOTENV_KEY}
        NODE_ENV: ${NODE_ENV}
    image: abdulachik/pugtube-worker
    working_dir: /app
    environment:
      - REDIS_URL=redis://cache:6379
    depends_on:
      cache:
        condition: service_healthy


  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cache: