services:
  api:
    image: abdulachik/api.pugtube.dev:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 250M
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
      DEBUG: True
    ports:
      - 8080:8080
    volumes:
      - ./api:/api

  web:
    image: abdulachik/www.pugtube.dev:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      api:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 250M
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_PATH: http://api:8000
      NEXTAUTH_URL: http://web:8000
      NO_SECRET: secret
    ports:
      - 3000:3000
    volumes:
      - ./web:/web

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_database: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    profiles:
      - debug
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pugtube.dev
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE='False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 5050:5050

  orion:
    image: abdulachik/orion.pugtube.dev:latest
    build:
      context: ./api
      dockerfile: orion.Dockerfile
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_API_PORT=4200
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/postgres
    ports:
      - 4200:4200
    volumes:
      - prefect:/root/.prefect
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  agent:
    image: abdulachik/agent.pugtube.dev:latest
    build:
      context: ./api
      dockerfile: agent.Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1G
    command: [ "prefect", "agent", "start", "-q", "default" ]
    environment:
      - PREFECT_API_URL=http://orion:4200/api
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
      - DEBUG=True
    depends_on:
      database:
        condition: service_healthy
      orion:
        condition: service_started
    restart: unless-stopped

volumes:
  database:
  pgadmin:
  prefect:
