name: Setup Python Environment
description: adds pdm, installs python and dependencies
inputs:
  env:
    description: this handles installing dependencies for testing or running tools
    default: 'prod'
    required: false
runs:
  using: "composite"
  steps:
    - uses: marocchino/tool-versions-action@v1
      id: versions

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ steps.versions.outputs.python }}
        token: ${{ github.token }}

    - uses: pdm-project/setup-pdm@v3
      name: Setup PDM
      with:
        python-version: ${{ steps.versions.outputs.python }}
        prerelease: true
        cache: true
        cache-dependency-path: |
          **/pdm.lock

