name: Setup Node.js Environment
description: adds node and npm and installs dependencies
inputs:
  env:
    description: this handles installing dependencies for testing or running tools
    default: 'prod'
    required: false
runs:
  using: "composite"
  steps:
    - uses: marocchino/tool-versions-action@v1
      id: versions

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.versions.outputs.nodejs }}
        token: ${{ github.token }}
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
