name: Webapp Compliance CI

on:
  push:
    paths:
      - 'web/**'
      - '.github/**'

defaults:
  run:
    shell: bash
    working-directory: web


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/setup_node
        with:
          env: 'dev'
      - run: |
          npm ci
          npm run lint

  test:
    needs: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/setup_node
        with:
          env: 'dev'

      - name: Run Tests
        run: |
          npm ci
          npm test

  release:
    needs: test
    runs-on: ubuntu-latest
    name: Release to www.pugtube.dev Docker Hub
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with:
          length: 8

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: orion.Dockerfile
          tags: abdulachik/www.pugtube.dev:latest,abdulachik/www.pugtube.dev:${{ steps.short-sha.outputs.sha }}
