# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    shell: bash

env:
  NODE_ENV: test
  REDIS_URL: redis://redis:6379/0
  HUSKY: 0
  DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
jobs:
  component:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Use Node.js ${{ steps.versions.outputs.nodejs}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nodejs}}

      - name: Load environment variables
        run: npx dotenv-vault pull ci .env -y -m=${{ secrets.DOTENV_ME }}

      - name: Cypress Component Tests
        uses: cypress-io/github-action@v5
        with:
          component: true
          record: true

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Use Node.js ${{ steps.versions.outputs.nodejs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}

      - name: Install Dependencies
        run: npm ci

      - name: Load environment variables
        run: npx dotenv-vault pull ci .env -y -m=${{ secrets.DOTENV_ME }}

      - name: Run Unit Tests
        run: npm run unit --runInBand --detectOpenHandles --forceExit --ci