# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    shell: bash

env:
  NODE_ENV: test
  DATABASE_URL: mysql://root:root@mysql:3306/test
  REDIS_URL: redis://redis:6379/0

jobs:
  component:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test

      redis:
        image: redis:latest


    steps:
      # - name: Install `Xvfb` for testing in CI/CD simulations
      #   if: ${{ env.ACT }}
      #   run: sudo apt-get update -y && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Checkout
        uses: actions/checkout@v3

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Use Node.js ${{ steps.versions.outputs.nodejs}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nodejs}}

      - name: Cypress Component Tests
        uses: cypress-io/github-action@v5
        with:
          component: true
          record: true
        env:
          HUSKY: 0
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_URL: ${{ env.DATABASE_URL }}
          REDIS_URL: ${{ env.REDIS_URL }}
          NODE_ENV: development
          GITHUB_ID: ${{ secrets.CLERK_GITHUB_ID }}
          GITHUB_SECRET: ${{ secrets.CLERK_GITHUB_SECRET }}
          DISCORD_ID: ${{ secrets.DISCORD_ID }}
          DISCORD_SECRET: ${{ secrets.DISCORD_SECRET }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
          AXIOM_DATASET: component-testing
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
